# This is core test runner
before_script:
  - apt-get install build-essential libssl-dev libffi-dev python-dev -y
  - pip install tox

sqlite:
  script:
  - tox

  tags:
  - sqlite

pgsql:
  script:
  - apt-get install build-essential libssl-dev libffi-dev python-dev python-psycopg2 -y
  - pip install tox psycopg2==2.6.1
  - psql -c 'create database django_leonardo;' -U postgres

  tags:
  - postgres
