# This is core test runner
before_script:
  - echo "deb http://ppa.launchpad.net/pypy/ppa/ubuntu trusty main" > /etc/apt/sources.list.d/pypy-ppa.list
  - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 2862D0785AFACD8C65B23DB0251104D968854915
  - apt-get update
  - apt-get install python-pip python-virtualenv python-memcache python-imaging python-docutils python-simplejson python-tz python-pygraphviz python-dev gettext libpq-dev libffi-dev libjpeg-dev -y
  - pip install tox
#
#pgsql:
#  script:
#  - tox -e py27-django18
#  - tox -e py27-django19
#
#  tags:
#  - postgres

sqlite:
  script:
  - export PBR_VERSION=1.2.3; tox -e py27-django18
  - export PBR_VERSION=1.2.3; tox -e py27-django19

  tags:
  - sqlite
